language: python

matrix:
  include:
  - sudo: required
    services:
      - docker
    env: PIP=pip
  - os: osx
    language: generic
    env: PIP=pip2

notifications:
  email: false

env:
  global:
    - TWINE_USERNAME=pyrundec
      # Note: TWINE_PASSWORD is set in Travis settings

script:
  - $PIP install cibuildwheel==0.10.0
  - cibuildwheel --output-dir wheelhouse
  # upload to PyPI
  - python -m pip install twine
  - python -m twine upload wheelhouse/*cp3*.whl
